/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
	queries: { key: 'buildInfo'; input: never; result: BuildInfo };
	mutations: never;
	subscriptions: { key: 'invalidateQuery'; input: never; result: InvalidateOperationEvent };
};

export interface BuildInfo {
	version: string;
	commit: string;
}

export interface InvalidateOperationEvent {
	key: string;
	arg: any;
}
